# Generated by Django 3.2.6 on 2021-08-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('charTittleId', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category/')),
                ('add_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('tittle', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post/')),
                ('url', models.CharField(max_length=300)),
                ('category',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startibloggers.category')),
            ],
        ),
    ]
